### ISSUE TITLE
RNaD Entropy Schedule

### ISSUE THREAD

**Issue by spktrm** [google-deepmind/open_spiel#1076] opened 2023-05-25 10:46 UTC
```python
s = EntropySchedule(sizes=(10,))
print([s(i) for i in range(20)])
[
(0.0, False), (0.2, False), (0.4, False), (0.6, False), (0.8, False), 
(1.0, False), (1.0, False), (1.0, False), (1.0, False), (1.0, False), 
(0.0, True), (0.2, False), (0.4, False), (0.6, False), (0.8, False), 
(1.0, False), (1.0, False), (1.0, False), (1.0, False), (1.0, False)
]
```
Shouldn't the alpha value be 1.0 when the regularization nets are updated?

Since it is 0 this effectively disrupts the linear interpolation between regularization policies

**Comment by lanctot** [comment] 2023-06-01 19:16
@perolat, @bartdevylder: any ideas?

**Comment by perolat** [comment] 2023-06-13 12:52
Hi @spktrm ,

Thanks for the question.

It should becomes 0 after we update the two regularisation policies. Unless we missed an edge case there should only be continuous interpolations between regularisation networks.

It should go this way:
- alpha goes from 0 to 1 linearly over half of the interval (interpolate from pi_{reg, 0} to pi_{reg, 1}),
- then alpha stays at one for the rest of the interval (here the regularisation policy is pi_{reg, 1}),
- we update the networks (to interpolate between pi_{reg, 1} and pi_{reg, 2})
- start a new interval from alpha=0 (so at the first step of this interval we start with the regularisation policy pi_{reg, 1})

Let me know if you see something that doesn't match this intended behaviour.

Julien

**Comment by lanctot** [comment] 2023-08-31 14:18
Update: We have identified this as a bug and Eugene Tarassov has a fix. Will be fixed on next sync to github.

**Closed** 2023-09-12 12:59 UTC
Labels: bug, fixed
